// <auto-generated />
using MediaStore.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaStore.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231030130354_ProductSeeding")]
    partial class ProductSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediaStore.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is a terrible movie",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/0/09/Suburbicon.jpg",
                            Price = 2.99m,
                            Title = "Suburbicon"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sliders is an American science fiction and fantasy television series created by Robert K. Weiss and Tracy Tormé. It was broadcast for five seasons between 1995 and 2000. The series follows a group of travelers as they use a wormhole to 'slide' between different parallel universes. Tracy Tormé, Robert K. Weiss, Leslie Belzberg, John Landis, David Peckinpah, Bill Dial and Alan Barnette served as executive producers at different times of the production. For its first two seasons, it was produced in Vancouver, British Columbia. It was filmed primarily in Los Angeles, California, in the last three seasons.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/e/e3/Sliders2.JPG",
                            Price = 29.99m,
                            Title = "Sliders (TV series)"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Charmed is an American fantasy drama television series created by Constance M. Burge and produced by Aaron Spelling and his production company Spelling Television, with Brad Kern serving as showrunner. The series was originally broadcast by The WB from October 7, 1998, until May 21, 2006",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/a/af/Charmedtitlelogo1.jpg",
                            Price = 29.99m,
                            Title = "Charmed"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Buffy the Vampire Slayer is a 1992 American comedy vampire film directed by Fran Rubel Kuzui and starring Kristy Swanson, Donald Sutherland, Paul Reubens, Rutger Hauer, Luke Perry, Hilary Swank, and David Arquette.",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/9/90/Buffy_Season_%281%29.jpg",
                            Price = 29.99m,
                            Title = "Buffy The Vampire Slayer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
